/*
 * This source file was generated by the Gradle 'init' task
 */
package org.td1;

import java.util.Scanner;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    Scanner scanner = new Scanner(System.in);

    System.out.print("Enter book title: ");
    String title = scanner.nextLine();

    System.out.print("Enter author full name: ");
    String author = scanner.nextLine();

    System.out.print("Enter book price: ");
    double price = scanner.nextDouble();

    // Creating a new Book object using the constructor
    Book book = new Book(title, author, price);

    // Displaying book details using the display method
    book.display();

    scanner.close();
  }
}
